/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linked.list.kth;

public class Library {


    public static void main(String[] args) {
        linkedListKth list = new linkedListKth();
        list.insert(1);
        list.insert(2);
        list.insert(3);
        list.insert(4);


            System.out.println("Linked List: " + list);
            System.out.println("kth from end k = 2: " + list.kthFromEnd(2));
            System.out.println("kth from end k = 4: " + list.kthFromEnd(4));
            System.out.println("kth from end k = 0: " + list.kthFromEnd(0));
            System.out.println("kth from end k = 0: " + list.kthFromEnd(6));







    }
}
