/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stack.queue.animal.shelter;

public class App {

    public static void main(String[] args) {
        AnimalShelter shelter = new AnimalShelter();

        // Enqueue some animals
        shelter.enqueue(new Animal("dog", "Buddy"));
        shelter.enqueue(new Animal("cat", "Whiskers"));
        shelter.enqueue(new Animal("dog", "Rex"));
        shelter.enqueue(new Animal("cat", "Smokey"));

        // Dequeue animals
        Animal adoptedDog = shelter.dequeue("dog");
        Animal adoptedCat = shelter.dequeue("cat");

        if (adoptedDog != null) {
            System.out.println("Adopted dog: " + adoptedDog.getName());
        } else {
            System.out.println("No dogs available for adoption.");
        }

        if (adoptedCat != null) {
            System.out.println("Adopted cat: " + adoptedCat.getName());
        } else {
            System.out.println("No cats available for adoption.");
        }
    }

}
