/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stack.and.queue;

public class App {

    public static void main(String[] arg) {
        Stack<Integer> stack = new Stack<>();

        for (int i = 0; i < 5; i++) {
            stack.Push(i);
            System.out.println(stack);
        }

        System.out.println("Peek " + stack.peek());
        System.out.println("new stack" + stack);


    Queue<Integer> queue = new Queue<>();

        for (int i = 0; i < 5; i++) {
            queue.enqueue(i);
            System.out.println(queue);
        }

}


}
