/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stack.queue.animal.shelter;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    private AnimalShelter shelter;

    @BeforeEach
    public void setUp() {
        shelter = new AnimalShelter();
    }

    @Test
    public void testEnqueueAndDequeue() {
        shelter.enqueue(new Animal("dog", "Buddy"));
        shelter.enqueue(new Animal("cat", "Whiskers"));
        shelter.enqueue(new Animal("dog", "Rex"));
        shelter.enqueue(new Animal("cat", "Smokey"));

        Animal adoptedDog = shelter.dequeue("dog");
        Animal adoptedCat = shelter.dequeue("cat");

        assertEquals("Buddy", adoptedDog.name);
        assertEquals("Whiskers", adoptedCat.name);
    }

    @Test
    public void testDequeueWithPreference() {
        shelter.enqueue(new Animal("dog", "Buddy"));
        shelter.enqueue(new Animal("cat", "Whiskers"));
        shelter.enqueue(new Animal("dog", "Rex"));
        shelter.enqueue(new Animal("cat", "Smokey"));

        Animal adoptedDog = shelter.dequeue("dog");
        Animal adoptedCat = shelter.dequeue("cat");

        assertEquals("Buddy", adoptedDog.name);
        assertEquals("Whiskers", adoptedCat.name);
    }

    @Test
    public void testDequeueWithoutPreference() {
        shelter.enqueue(new Animal("dog", "Buddy"));
        shelter.enqueue(new Animal("cat", "Whiskers"));

        Animal adoptedAnimal = shelter.dequeue("any");

        assertEquals("Buddy", adoptedAnimal.name);
    }

    @Test
    public void testDequeueEmptyShelter() {
        Animal adoptedDog = shelter.dequeue("dog");

        assertNull(adoptedDog);
    }
}
